server:
  port: 9000
spring:
  application:
    name: ad_gateway
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

#zuul:
#  prefix: /IdeaProjects
#  routes:
#    sponsor:
#      path: /ad-sponsor/**
#      serviceId: eureka-client-ad-sponsor
#      strip-prefix: false
#    search:
#      path: /ad-search/**
#      serviceId: eureka-client-ad-search
#      strip-prefix: false